command:
    resource: "@commandBundle/Resources/config/routing.yml"
    prefix:   /



patient:
    resource: "@PatientBundle/Resources/config/routing.yml"
    prefix:   /

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /

users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /

koko:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix:   /

JMSJobQueueBundle:
    resource: "@JMSJobQueueBundle/Controller/"
    type: annotation
    prefix: /jobs