configuration_indllex:
    path:     /
    defaults: { _controller: "EvenementBundle:Configuration:index" }
    methods:  GET

configuration_show:
    path:     /{id}/show
    defaults: { _controller: "EvenementBundle:Configuration:show" }
    methods:  GET

configuration_new:
    path:     /new
    defaults: { _controller: "EvenementBundle:Configuration:new" }
    methods:  [GET, POST]

configuration_edit:
    path:     /{id}/edit
    defaults: { _controller: "EvenementBundle:Configuration:edit" }
    methods:  [GET, POST]

configuration_delete:
    path:     /{id}/delete
    defaults: { _controller: "EvenementBundle:Configuration:delete" }
    methods:  DELETE
