delimiteur_index:
    path:     /
    defaults: { _controller: "EvenementBundle:Delimiteur:index" }
    methods:  GET

delimiteur_show:
    path:     /{id}/show
    defaults: { _controller: "EvenementBundle:Delimiteur:show" }
    methods:  GET

delimiteur_new:
    path:     /new
    defaults: { _controller: "EvenementBundle:Delimiteur:new" }
    methods:  [GET, POST]

delimiteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "EvenementBundle:Delimiteur:edit" }
    methods:  [GET, POST]

delimiteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "EvenementBundle:Delimiteur:delete" }
    methods:  DELETE
