<?php

namespace EvenementBundle\Repository;

/**
 * DelimiteurTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelimiteurTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
