<?php

namespace EvenementBundle\Repository;

/**
 * DelimiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelimiteurRepository extends \Doctrine\ORM\EntityRepository
{
}
