<?php

namespace EvenementBundle\Repository;

/**
 * RdvTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdvTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
