event_task:
    resource: "@EventBundle/Resources/config/routing/task.yml"
    prefix:   /task

event_homepage:
    path:     /
    defaults: { _controller: EventBundle:Task:new }

show_task:
    path:    /{id}/showT
    defaults: { _controller: EventBundle:Task:showJson }
edit_task:
    path:    /{id}/edit
    defaults: { _controller: EventBundle:Task:edit }